appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: A0YVHQyNM51Y88wEpnANa1UOpOPdXCdqppyz5jqyDx63vn4iNrfXF6P/uP3J3TE1aZrNsRAwLuuVr6RaRmDdnOwEQEADwtA4zUQ0K+WkLS48BSX866arU24OM860JnuP8cFE2x1IjKicrSsEf7bvfz49XOBLMGawMMymahI3OpNygnxg9TguVR89JiUeh1FEWvx4TaS2V+pttksr1NW5m5rI+tujeVUQvtuc3bFvrN6Zi76g7nqJnSmUi7PCDLNYmursCBy5ax6jbhlHCXoi+9WEPTwHLXQYviZlumS/YaxmnDGySFrc+Csp+A6EC9r+d43+jEofqkc7ms2tPkVzUyx8mQLXhkX714tpGK3eI0ZHkj3+DEiV0NdHChINLEYW3D1LoFoYeyEbeVLps5a/S1w198ZQUZ7khGKDFwNzzyod2rSIkizKhkBIf4CFqSACMKYNGvEcwhfAEMMrDdulVXZxHZK7cnz5UosSeUESlH9uJR53/z0GKLYEr5Cl0m3KYp8mkqKoXklIrA4VwEzElRsj9bRzgHxPVyUQDWZt8UFgc4DrDpvp2qdwPwy3sz27kKU+Fzu437FhEA1pf1s75vKe7ysnlX429ikTVS3kQkwfgZBkfdWOSMrWWhxM7Sp0gLc0qf8BYherJ1sviuypa/etOLX4L3prE3piRn1C1BU=}
bot:
  automerge: true
